name: Build and deploy Node.js app to Azure Web App - recipe-ai-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Set up Node.js version
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npm run test --if-present

      - name: Check build folder
        run: ls -la build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: build/
      - name: Check the build folder
        run: ls -la build

      # - name: 'Deploy to Azure Web App'
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'recipe-ai-api'
      #     slot-name: 'Production'
      #     publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0C5EF1DE7F814B4AADA8DF5CEF0F2013 }}
      #     package: build/

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp 
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: 'recipe-ai-api'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0C5EF1DE7F814B4AADA8DF5CEF0F2013 }}
          package: .